### ISSUE TITLE
Error while moving to matching block

### ISSUE THREAD

**Issue by yonson2** [jlcrochet/vim-crystal#1]
Everytime I try to navigate to matching block (i.e. when pressing `%`) I get a bunch of errors:

```
Error detected while processing function matchit#Match_wrapper[84]..<SNR>73_Wholematch:
line    5:
E866: (NFA regexp) Misplaced @
Error detected while processing function matchit#Match_wrapper:
line   85:
E866: (NFA regexp) Misplaced @
Press ENTER or type command to continue
```

I'm running neovim v0.5.0 and crystal 1.1.1 if that helps, if you need any more info I'll gladly provide it.

**Comment by jlcrochet** [comment]
Sorry about that, I never really tested the vim-matchit support. It should work now.

**Comment by yonson2** [comment]
It works perfectly now! thanks for the quick fix!
